app_id: 7c214080-8ada-4d78-a056-bee56cae2a3b
app_secret: n5w8Q~O1DXWYj9xRY_zP4pAPYsQnNo4t8niMkdBF
redirect: "https://printing-portal.herokuapp.com/printing_portal/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "https://login.microsoftonline.com/common"
